---
language: python
python:
  - "2.7"
env:
  global:
    - ODM_THEME_HOME=/usr/lib/ckan/default/src/ckanext-odm_theme
    - TESTS_FOLDER=/usr/lib/ckan/default/src/ckanext-odm_theme/ckanext/odm_theme/tests
install:
  - "sudo mkdir -p /usr/lib/ckan/default"
  - "sudo chown `whoami` /usr/lib/ckan/default"
  - "virtualenv --no-site-packages /usr/lib/ckan/default"
  - ". /usr/lib/ckan/default/bin/activate"

  # Download CKAN 2.3 (own clone) stable release
  - "pip install -e 'git+https://github.com/OpenDevelopmentMekong/ckan-2.3.git@master#egg=ckan'"
  - "pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt"
  - "pip install -r /usr/lib/ckan/default/src/ckan/dev-requirements.txt"

  # Set up the databases
  - "echo '*:*:*:*:ckan_default_pass' > ~/.pgpass"
  - "sudo -u postgres createuser -S -D -R ckan_default"
  - "sudo -u postgres createdb -O ckan_default ckan_default -E utf-8"

  # Set up the test databases
  - sudo -u postgres createdb -O ckan_default ckan_test -E utf-8
  - sudo -u postgres createdb -O ckan_default datastore_test -E utf-8
  - paster datastore set-permissions -c $ODM_THEME_HOME/test.ini | sudo -u postgres psql

  - "sudo mkdir -p /etc/ckan/default"
  - "sudo chown -R `whoami` /etc/ckan/"

  # Install ckanapi, needed by tests
  - "cd /usr/lib/ckan/default/src/ckan"
  - "pip install -e 'git+https://github.com/ckan/ckanapi.git@ckanapi-3.3#egg=ckanapi'"

  # Clone plugin
  - "mkdir -p $ODM_THEME_HOME"
  - "cd $ODM_THEME_HOME"
  - "git clone --depth 1 https://github.com/OpenDevelopmentMekong/ckanext-odm_theme.git ."
  - "pip install -r requirements.txt"
  - "python setup.py develop"

  # Install Jetty and configure solr
  - "sudo apt-get update"
  - "sudo apt-get install --yes solr-jetty"
  - "cd /etc/default"
  - "sudo echo 'NO_START=0' | sudo tee -a jetty"
  - "sudo echo 'JETTY_HOST=127.0.0.1' | sudo tee -a jetty"
  - "sudo echo 'JETTY_PORT=8080' | sudo tee -a jetty"
  - "sudo echo 'JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64/' | sudo tee -a jetty"

  # Start Jetty, link Solr schema.xml
  - "sudo service jetty start"
  - "sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak"
  - "sudo ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml"
  - "sudo service jetty restart"

  # Init DB
  - "cd /usr/lib/ckan/default/src/ckan"
  - "paster db init -c $ODM_THEME_HOME/test.ini"
  - "ln -s $ODM_THEME_HOME/test-who.ini /etc/ckan/default/who.ini"

script: "nosetests --ckan --with-pylons=$ODM_THEME_HOME/test.ini $TESTS_FOLDER"
