---
language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y python-dev postgresql libpq-dev python-pip python-virtualenv git-core solr-jetty openjdk-6-jdk"
  - "mkdir -p ~/ckan/lib"
  - "sudo ln -s ~/ckan/lib /usr/lib/ckan"
  - "mkdir -p ~/ckan/etc"
  - "sudo ln -s ~/ckan/etc /etc/ckan"
  - "sudo mkdir -p /usr/lib/ckan/default"
  - "sudo chown `whoami` /usr/lib/ckan/default"
  - "virtualenv --no-site-packages /usr/lib/ckan/default"
  - ". /usr/lib/ckan/default/bin/activate"
  # Download CKAN 2.2 stable release
  - "pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.2#egg=ckan'"
  - "pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt"
  - deactivate
  - ". /usr/lib/ckan/default/bin/activate"
  # Pasting password into ~/.pgpass to bypass password prompt while running createuser
  - "echo '*:*:*:*:ckan_default_pass' > ~/.pgpass"
  - "sudo -u postgres createuser --no-password -S -D -R ckan_default"
  - "sudo -u postgres createdb -O ckan_default ckan_default -E utf-8"
  - "sudo mkdir -p /etc/ckan/default"
  - "sudo chown -R `whoami` /etc/ckan/"
  # Dynamic editing of ini file could be an alternative for downloading raw files
  #- "cd /usr/lib/ckan/default/src/ckan"
  #- "paster make-config ckan /etc/ckan/default/development.ini"
  #- "sed -i.bak '/^sqlalchemy.url=/s/=.*/=postgresql://ckan_default:ckan_default_pass@localhost/ckan_default/' /etc/ckan/default/development.ini"
  #- "sed -i.bak '/^ckan.site_id=/s/=.*/=default' /etc/ckan/default/development.ini"
  # Download raw config files from github: development.ini and jetty
  - "cd /etc/ckan/default"
  - "sudo wget -O development.ini https://raw.githubusercontent.com/OpenDevelopmentMekong/odm-scripting/deployment-scripts/deployment-scripts/ckan_deployment/development.ini?token=384894__eyJzY29wZSI6IlJhd0Jsb2I6T3BlbkRldmVsb3BtZW50TWVrb25nL29kbS1zY3JpcHRpbmcvZGVwbG95bWVudC1zY3JpcHRzL2RlcGxveW1lbnQtc2NyaXB0cy9ja2FuX2RlcGxveW1lbnQvZGV2ZWxvcG1lbnQuaW5pIiwiZXhwaXJlcyI6MTQxMjIwMjA5N30%3D--4507b08d36e6d26a7c7913b6af68904d36a874b0"
  - "cd /etc/default"
  - "sudo wget -O jetty https://raw.githubusercontent.com/OpenDevelopmentMekong/odm-scripting/deployment-scripts/deployment-scripts/ckan_deployment/jetty?token=384894__eyJzY29wZSI6IlJhd0Jsb2I6T3BlbkRldmVsb3BtZW50TWVrb25nL29kbS1zY3JpcHRpbmcvZGVwbG95bWVudC1zY3JpcHRzL2RlcGxveW1lbnQtc2NyaXB0cy9ja2FuX2RlcGxveW1lbnQvamV0dHkiLCJleHBpcmVzIjoxNDEyMTcwMTMwfQ%3D%3D--18b9c4caa2e60fb2ffac45c0285c309d79f95483"
  # Once the repo becomes public, instead of the lines above, we clone odm-scripting repo and copy config files to the path they belong: development.ini and jetty
  #- "mkdir -p /usr/lib/ckan/default/src/odm-scripting"
  #- "cd /usr/lib/ckan/default/src/odm-scripting"
  #- "git clone -b deployment-scripts https://github.com/OpenDevelopmentMekong/odm-scripting.git ."
  #- "cp -fr deployment-scripts/development.ini /etc/ckan/default"
  #- "cp -fr deployment-scripts/jetty /etc/default"
  - "sudo service jetty start"
  - "sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak"
  - "sudo ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml"
  - "sudo service jetty restart"
  - "cd /usr/lib/ckan/default/src/ckan"
  # Init DB
  - "paster db init -c /etc/ckan/default/development.ini"
  - "ln -s /usr/lib/ckan/default/src/ckan/who.ini /etc/ckan/default/who.ini"
  # Install ckanapi, needed by tests
  - "pip install -e 'git+https://github.com/ckan/ckanapi.git@ckanapi-3.3#egg=ckanapi'"
  - "mkdir -p /usr/lib/ckan/default/src/ckanext-odm_theme"
  - "cd /usr/lib/ckan/default/src/ckanext-odm_theme/"
  # Clone
  - "git clone https://github.com/OpenDevelopmentMekong/ckanext-odm_theme.git ."
env:
  matrix:
    - TESTS_HOME=/usr/lib/ckan/default/src/ckanext-odm_theme
install:
  - "pip install -r requirements.txt"
script: "nosetests --ckan --with-pylons=/etc/ckan/default/development.ini $TESTS_HOME/ckanext/odm_theme/tests/"
