---
language: python
python:
  - "2.7"
env:
  global:
    - TESTS_HOME=/usr/lib/ckan/default/src/ckanext-odm_theme
    - TESTS_FOLDER=/usr/lib/ckan/default/src/ckanext-odm_theme/ckanext/odm_theme/tests
install:
  # - "mkdir -p ~/ckan/lib"
  # - "sudo ln -s ~/ckan/lib /usr/lib/ckan"
  # - "mkdir -p ~/ckan/etc"
  # - "sudo ln -s ~/ckan/etc /etc/ckan"
  - "sudo mkdir -p /usr/lib/ckan/default"
  - "sudo chown `whoami` /usr/lib/ckan/default"
  - "virtualenv --no-site-packages /usr/lib/ckan/default"
  - ". /usr/lib/ckan/default/bin/activate"

  # Download CKAN 2.2 stable release
  - "pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.2#egg=ckan'"
  - "pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt"
  - "pip install -r /usr/lib/ckan/default/src/ckan/dev-requirements.txt"

  # Set up the databases
  - "echo '*:*:*:*:ckan_default_pass' > ~/.pgpass"
  - "sudo -u postgres createuser -S -D -R ckan_default"
  - "sudo -u postgres createdb -O ckan_default ckan_default -E utf-8"

  # Set up the test databases
  - sudo -u postgres createdb -O ckan_default ckan_test -E utf-8
  - sudo -u postgres createdb -O ckan_default datastore_test -E utf-8
  - paster datastore set-permissions -c test-core.ini | sudo -u postgres psql

  - "sudo mkdir -p /etc/ckan/default"
  - "sudo chown -R `whoami` /etc/ckan/"

  # Install ckanapi, needed by tests
  - "cd /usr/lib/ckan/default/src/ckan"
  - "pip install -e 'git+https://github.com/ckan/ckanapi.git@ckanapi-3.3#egg=ckanapi'"

  # Clone plugin
  - "mkdir -p $TESTS_HOME"
  - "cd $TESTS_HOME"
  - "git clone -b importing-term-translations https://github.com/OpenDevelopmentMekong/ckanext-odm_theme.git ."
  - "pip install -r requirements.txt"
  - "python setup.py develop"

  # Install Jetty and configure solr
  - "sudo apt-get install --yes solr-jetty"
  - "cd /etc/default"
  - "sudo wget -O jetty https://raw.githubusercontent.com/OpenDevelopmentMekong/odm-scripting/deployment-scripts/deployment-scripts/ckan_deployment/jetty?token=384894__eyJzY29wZSI6IlJhd0Jsb2I6T3BlbkRldmVsb3BtZW50TWVrb25nL29kbS1zY3JpcHRpbmcvZGVwbG95bWVudC1zY3JpcHRzL2RlcGxveW1lbnQtc2NyaXB0cy9ja2FuX2RlcGxveW1lbnQvamV0dHkiLCJleHBpcmVzIjoxNDEyMTcwMTMwfQ%3D%3D--18b9c4caa2e60fb2ffac45c0285c309d79f95483"

  # Start Jetty, link Solr schema.xml
  - "sudo service jetty start"
  - "sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak"
  - "sudo ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml"
  - "sudo service jetty restart"

  # Init DB
  - "cd /usr/lib/ckan/default/src/ckan"
  - "paster db init -c $TESTS_HOME/test.ini"
  - "ln -s /usr/lib/ckan/default/src/ckan/who.ini /etc/ckan/default/who.ini"

script: "nosetests --ckan --with-pylons=$TESTS_HOME/test.ini $TESTS_FOLDER"
